### ISSUE TITLE
muse code?

### ISSUE THREAD

**Issue by xinqipony** [lancopku/MUSE#1]
nice work here and I really love the results of this paper, just wonder is the muse code already  in this repo?

**Comment by zhaoguangxiang** [comment]
Yes, code Is already available, instructions for training are in the examples/parallel_multi-scale_attention/readme.md,  see the combine_transformer.py and transformer_bm(means big matrix, code for acceleration) in the fairseq/models for the main code, the idea to combine convolution and self attention is in the fairseq/moudules/multihead_attention.py.
