### ISSUE TITLE
anyone running into 'nan'

### ISSUE THREAD

**Issue by xinqipony** [lancopku/MUSE#6]
I am changing the TransformerCombineEncoder to do a seq to seq job, but I got 'nan' after some steps, anyone has experience on this?

**Comment by zhaoguangxiang** [comment]
What is your change? Could the TransformerEncoder work for your task.

**Comment by xinqipony** [comment]
I'm training a machine translation task and using TransformerCombineEncoderLayer, which uses MultiheadAttention820, is it the best in the MUSE paper?

**Comment by zhaoguangxiang** [comment]
> I'm training a machine translation task and using TransformerCombineEncoderLayer, which uses MultiheadAttention820, is it the best in the MUSE paper?

Yes,   but the hyper-paramenter for model configuration which dermines the actual model you use  is important.

**Comment by xinqipony** [comment]
I see. thx, I will re try using different hyper-paramenters;
